create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('agenda','empresa','newsletter')),
  email text not null,
  name text, phone text, company text, city text, service text, message text, source text,
  created_at timestamptz not null default now()
);
alter table public.leads enable row level security;
-- solo el servicio (service key) escribe/lee; sin políticas públicas
